import sys
import os

# Define your character-to-tile-ID dictionary here
TILE_MAP = {
    '.': 0x00,  # Tile
    '1': 0x01,  # Tile
    '2': 0x02,  # Tile
}

def parse_map(input_file, output_file, label_name):
    # Read the text file, ignoring empty lines
    with open(input_file, 'r') as f:
        lines = [line.strip('\n') for line in f if line.strip()]

    # Validate screen dimensions
    if len(lines) != 24:
        print(f"Warning: Expected 24 rows, found {len(lines)} in {input_file}")

    with open(output_file, 'w') as out:
        out.write("; =================================================================\n")
        out.write("; AUTOGENERATED FILE - DO NOT EDIT MANUALLY\n")
        out.write(f"; Generated from {input_file}\n")
        out.write("; =================================================================\n\n")
        
        out.write(f"{label_name}:\n")
        
        for row_idx, line in enumerate(lines):
            # Pad with empty tiles if the line is shorter than 32 chars
            line = line.ljust(32, '.') 
            if len(line) > 32:
                print(f"Warning: Row {row_idx} is longer than 32 characters. Truncating.")
                line = line[:32]
            
            hex_values = []
            for char in line:
                tile_id = TILE_MAP.get(char, 0x00) # Default to 0x00 if character isn't found
                hex_values.append(f"${tile_id:02X}")
            
            # Write 32 bytes per row using defb
            out.write(f"  defb {', '.join(hex_values)}  ; Row {row_idx}\n")

if __name__ == "__main__":
    # Example usage: python3 map_parser.py stage1.txt stage1_map.asm stage1_map
    # You can easily wrap this in a bash script or Makefile
    if len(sys.argv) == 4:
        parse_map(sys.argv[1], sys.argv[2], sys.argv[3])
    else:
        print("Usage: python3 map_parser.py <input.txt> <output.asm> <label_name>")

