#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys


def convert_tile_data(input_path, output_path):
    try:
        with open(input_path, "r") as f_in, open(output_path, "w") as f_out:

            # --- Write the auto-generated warning header to the output file ---
            f_out.write("; " + "=" * 65 + "\n")
            f_out.write("; AUTOGENERATED FILE - DO NOT EDIT MANUALLY\n")
            f_out.write(
                "; This file was automatically generated by the tiles_parser.py tool.\n"
            )
            f_out.write("; Any manual modifications will be overwritten.\n")
            f_out.write("; " + "=" * 65 + "\n\n")

            row = 0
            for line in f_in:
                line = line.strip()

                # Skip empty lines
                if not line:
                    continue

                # Handle the tile label
                if line.startswith("--"):
                    tile_name = line.replace("--", "").strip()
                    f_out.write(f"{tile_name}_pattern:\n")
                    row = 0

                # Handle the binary rows
                else:
                    # Pad the binary string with spaces to align the comments nicely
                    f_out.write(f"  defb %{line:8}    ; Row {row}\n")
                    row += 1

        print(f"Successfully converted tiles to {output_path}")

    except FileNotFoundError:
        print(f"Error: Could not find the input file '{input_path}'")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python tiles_parser.py <input_file.txt> <output_file.asm>")
        sys.exit(1)

    convert_tile_data(sys.argv[1], sys.argv[2])

