; =================================================================
; AUTOGENERATED FILE - DO NOT EDIT MANUALLY
; This file was automatically generated by the assets_parser.py tool.
; Any manual modifications will be overwritten.
; =================================================================

sprite_patterns_start:
bloke_running_left_pattern:
  defb %00110000    ; Row 0
  defb %00110000    ; Row 1
  defb %00011100    ; Row 2
  defb %01111010    ; Row 3
  defb %00011000    ; Row 4
  defb %00100100    ; Row 5
  defb %00100010    ; Row 6
  defb %00100000    ; Row 7
sprite_patterns_end:
