; =================================================================
; AUTOGENERATED FILE - DO NOT EDIT MANUALLY
; This file was automatically generated by the tiles_parser.py tool.
; Any manual modifications will be overwritten.
; =================================================================

tile0_pattern:
  defb %11011111    ; Row 0
  defb %11011111    ; Row 1
  defb %11011111    ; Row 2
  defb %00000000    ; Row 3
  defb %11111101    ; Row 4
  defb %11111101    ; Row 5
  defb %11111101    ; Row 6
  defb %11111101    ; Row 7
