; =================================================================
; AUTOGENERATED FILE - DO NOT EDIT MANUALLY
; This file was automatically generated by the assets_parser.py tool.
; Any manual modifications will be overwritten.
; =================================================================

tile_patterns_start:
tile0_pattern:
  defb %00111111    ; Row 0
  defb %10011111    ; Row 1
  defb %11001111    ; Row 2
  defb %00000000    ; Row 3
  defb %11100111    ; Row 4
  defb %11110011    ; Row 5
  defb %11111001    ; Row 6
  defb %11111100    ; Row 7
tile1_pattern:
  defb %11011111    ; Row 0
  defb %11011111    ; Row 1
  defb %11011111    ; Row 2
  defb %00000000    ; Row 3
  defb %11111101    ; Row 4
  defb %11111101    ; Row 5
  defb %11111101    ; Row 6
  defb %11111101    ; Row 7
tile_patterns_end:
